#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLServices.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GameDB_01")]
	public partial class GameDB_01DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOnlineLog(OnlineLog instance);
    partial void UpdateOnlineLog(OnlineLog instance);
    partial void DeleteOnlineLog(OnlineLog instance);
    #endregion
		
		public GameDB_01DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GameDB_01ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GameDB_01DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GameDB_01DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GameDB_01DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GameDB_01DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OnlineLog> OnlineLogs
		{
			get
			{
				return this.GetTable<OnlineLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnlineLog")]
	public partial class OnlineLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogId;
		
		private System.DateTime _LogTime;
		
		private int _TotalCCU;
		
		private System.Data.Linq.Binary _ZonesCCU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIdChanging(int value);
    partial void OnLogIdChanged();
    partial void OnLogTimeChanging(System.DateTime value);
    partial void OnLogTimeChanged();
    partial void OnTotalCCUChanging(int value);
    partial void OnTotalCCUChanged();
    partial void OnZonesCCUChanging(System.Data.Linq.Binary value);
    partial void OnZonesCCUChanged();
    #endregion
		
		public OnlineLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogId
		{
			get
			{
				return this._LogId;
			}
			set
			{
				if ((this._LogId != value))
				{
					this.OnLogIdChanging(value);
					this.SendPropertyChanging();
					this._LogId = value;
					this.SendPropertyChanged("LogId");
					this.OnLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogTime", DbType="SmallDateTime NOT NULL")]
		public System.DateTime LogTime
		{
			get
			{
				return this._LogTime;
			}
			set
			{
				if ((this._LogTime != value))
				{
					this.OnLogTimeChanging(value);
					this.SendPropertyChanging();
					this._LogTime = value;
					this.SendPropertyChanged("LogTime");
					this.OnLogTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCCU", DbType="Int NOT NULL")]
		public int TotalCCU
		{
			get
			{
				return this._TotalCCU;
			}
			set
			{
				if ((this._TotalCCU != value))
				{
					this.OnTotalCCUChanging(value);
					this.SendPropertyChanging();
					this._TotalCCU = value;
					this.SendPropertyChanged("TotalCCU");
					this.OnTotalCCUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZonesCCU", DbType="VarBinary(32)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ZonesCCU
		{
			get
			{
				return this._ZonesCCU;
			}
			set
			{
				if ((this._ZonesCCU != value))
				{
					this.OnZonesCCUChanging(value);
					this.SendPropertyChanging();
					this._ZonesCCU = value;
					this.SendPropertyChanged("ZonesCCU");
					this.OnZonesCCUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
